kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

services:
  - name: nats-streaming
    image: nats-streaming
    command: [-mc, 0]
    ports:
      - 4222

steps:
  - name: tests
    image: golang:1.12
    environment:
      CODECOV_TOKEN:
        from_secret: CODECOV_TOKEN
      COVERALLS_TOKEN:
        from_secret: COVERALLS_TOKEN
    commands:
      - export STAN_HOST="nats-streaming"
      - export NATS_HOST="nats-streaming"
      - go build ./moleculerjs
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
      - export NVM_DIR="${XDG_CONFIG_HOME/:-$HOME/.}nvm"
      - [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      - nvm install 10
      - cd ./moleculerjs
      - pwd
      - npm install
      - cd ..
      - go run github.com/onsi/ginkgo/ginkgo -r --randomizeAllSpecs --failFast --cover --trace
      - go run github.com/modocache/gover ./ coverage.txt
      - curl -s https://codecov.io/bash | bash || echo "Error uploading codecov"
      - go run github.com/mattn/goveralls -coverprofile=coverage.txt -service=drone.io || echo "Error uploading coveralls"
